"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from importlib.util import find_spec
import os

# ----------------------------
# Paths
# ----------------------------
# This file lives at: src/core/settings.py
SETTINGS_DIR = Path(__file__).resolve().parent  # .../src/core
SRC_DIR = SETTINGS_DIR.parent  # .../src
BASE_DIR = SRC_DIR.parent  # project-root

# ----------------------------
# Security & Debug
# ----------------------------
# IMPORTANT: Set DJANGO_SECRET_KEY in your environment for anything beyond local dev.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-insecure-secret-key")

# DEBUG: default True for local POC, but override via env in CI/Prod
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes")

# Comma-separated list: e.g. "localhost,127.0.0.1,myapp.example.com"
ALLOWED_HOSTS = [
    h for h in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h
]

# Optional: CSRF Trusted Origins (needed when serving behind a domain with HTTPS)
# Comma-separated full origins: e.g. "https://myapp.example.com,https://staging.example.com"
CSRF_TRUSTED_ORIGINS = [
    o for o in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o
]
USE_X_FORWARDED_HOST = True if os.getenv("LOCAL_DEVELOPMENT", None) else False
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if os.getenv("LOCAL_DEVELOPMENT", None)
    else None
)

# ----------------------------
# Applications
# ----------------------------
INSTALLED_APPS = [
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "django_htmx",
    # Internal
    "core",
]

# ----------------------------
# Middleware
# ----------------------------
HAS_WHITENOISE = find_spec("whitenoise") is not None

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Django core
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # HTMX helper (adds request.htmx, etc.)
    "django_htmx.middleware.HtmxMiddleware",
]

if HAS_WHITENOISE:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "core.urls"

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"

# ----------------------------
# Templates
# ----------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Project-level shared templates take precedence
        "DIRS": [
            SRC_DIR / "templates",
        ],
        "APP_DIRS": True,  # Also discover <app>/templates/
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]

# ----------------------------
# Database
# ----------------------------
# Honor DATABASE_URL if provided.
# Example: postgres: "postgresql://user:pass@host:5432/dbname"
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

if DATABASE_URL:
    # Minimal parser that works for common schemes; for production, consider dj-database-url
    from urllib.parse import urlparse

    parsed = urlparse(DATABASE_URL)
    ENGINE_MAP = {
        "postgres": "django.db.backends.postgresql",
        "postgresql": "django.db.backends.postgresql",
        "psql": "django.db.backends.postgresql",
        "mysql": "django.db.backends.mysql",
        "sqlite": "django.db.backends.sqlite3",
        "sqlite3": "django.db.backends.sqlite3",
    }
    ENGINE = ENGINE_MAP.get(parsed.scheme, "django.db.backends.postgresql")

    if ENGINE.endswith("sqlite3"):
        NAME = parsed.path[1:] if parsed.path else (BASE_DIR / "db.sqlite3")
    else:
        NAME = parsed.path[1:]
    DATABASES = {
        "default": {
            "ENGINE": ENGINE,
            "NAME": NAME,
            "USER": parsed.username or "",
            "PASSWORD": parsed.password or "",
            "HOST": parsed.hostname or "",
            "PORT": parsed.port or "",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# ----------------------------
# Static & Media
# ----------------------------
STATIC_URL = "/static/"

# During development (DEBUG=True), Django will serve:
#  - project-level static from SRC_DIR / "static"
#  - app-level static from <app>/static/<app>/...
STATICFILES_DIRS = [
    SRC_DIR / "static",
]

# Where collectstatic will gather files for production serving
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if HAS_WHITENOISE
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

# Media (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ----------------------------
# Internationalization / Time
# ----------------------------
LANGUAGE_CODE = os.getenv("DJANGO_LANGUAGE_CODE", "en-us")
TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "UTC")
USE_I18N = True
USE_TZ = True

# ----------------------------
# Auth / Primary Key
# ----------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ----------------------------
# Security toggles for non-DEBUG
# ----------------------------
if not DEBUG:
    # Sensible defaults; adjust via env or split later into production settings
    SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "true").lower() in (
        "1",
        "true",
        "yes",
    )
    SESSION_COOKIE_SECURE = os.getenv(
        "DJANGO_SESSION_COOKIE_SECURE", "true"
    ).lower() in ("1", "true", "yes")
    CSRF_COOKIE_SECURE = os.getenv("DJANGO_CSRF_COOKIE_SECURE", "true").lower() in (
        "1",
        "true",
        "yes",
    )
    SECURE_HSTS_SECONDS = int(
        os.getenv("DJANGO_SECURE_HSTS_SECONDS", "2592000")
    )  # 30 days
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv(
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "true"
    ).lower() in ("1", "true", "yes")
    SECURE_HSTS_PRELOAD = os.getenv("DJANGO_SECURE_HSTS_PRELOAD", "true").lower() in (
        "1",
        "true",
        "yes",
    )

# ----------------------------
# Logging (minimal, dev-friendly)
# ----------------------------
LOGLEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "[{levelname}] {name}: {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "root": {"handlers": ["console"], "level": LOGLEVEL},
}

# ----------------------------
# Additional Settings and Misc
# ----------------------------
APPEND_SLASH = True
